### ISSUE TITLE
Queue breaks public url usage

### ISSUE THREAD

**Issue by Jpkovas** [hlky/stable-diffusion-webui#10]
With the queue enabled, sharing the public url with "share=True" makes the submit button do nothing.

**Comment by hlky** [comment]
going to need a bit more information

any console output?

**Comment by Jpkovas** [comment]
No, it really don't do anything on the console, it's like no one submitted anything, but only in the public url usage, the localhost one works fine

**Comment by EyeDeck** [comment]
Turning on the queue will do this if your browser still has the old page cached. Try Shift+F5 (or was it ctrl+F5?) to update, should work after that.

**Comment by hlky** [comment]
so queuing works as intended on local? can you just port forward and use dynamic dns as a workaround? i don't see what the issue could be because the docs say it essentially does that `served through a Gradio URL, we are only a proxy for your local server`

btw if you're sharing this publicly you might want to add authentication to demo.launch()

```
auth=("admin", "pass1234")
```

**Comment by Jpkovas** [comment]
port foward works, but the clean cache doesn't, I will close the issue for now
