### ISSUE TITLE
Save original copy of image before upscaling or face fixing

### ISSUE THREAD

**Issue by Vyviel** [hlky/stable-diffusion-webui#103]
Thanks for this really useful tool!

It would be really helpful for my workflow if when toggling on the upscale images and fix faces options that it also gave you the option to save a copy of the image before upscaling or before face fixing or both.

This is because I find that sometimes the original face is superior to the fixed one plus I am sometimes interested in running the original 512x512 output file through a different upscaler etc.

It could be something as simple as saving the original file like normal then appending to the end of the filename something like "FF" "4xUP" etc depending on which options were selected.

Also makes it easier when sorting my folders as sometimes I upscale some with the same prompt and some are originals so the only way to tell is to look at file sizes and its not really possible to tell with the face fixes as the file size is about the same 500kb

**Comment by hlky** [comment]
done [b9b7432](https://github.com/hlky/stable-diffusion-webui/commit/b9b74329ae416179d7d4b9302f7eaa5afaca279e)

**Comment by ZeroCool940711** [comment]
@hlky any chance you or someone else could add an option to disable this feature?
In my case I have no use for the extra images and I'm just interested on the final image after it has been processed by GFPGAN/RealESRGAN. The extra images end up using a lot of extra space when generating a lot of images or just over time unless you clean the folders regularly, it also makes a mess in the output folder as each extra image also has a `yml` file with them if you use the "Write info files" option which is on by default, instead of saving all the images been the default option and/or been forced I think it would be better to have a toggle for this feature and be something optional.
