### ISSUE TITLE
[BUG] Duplicate images are saved as separate files GFPGAN + RealESRGAN + Regular. NEED A FIX |details inside|

### ISSUE THREAD

**Issue by search620** [hlky/stable-diffusion-webui#189]
The images are saved separately although the setting is only for specific parameters.

For example:
I want generate images with GFPGAN + RealESRGAN but I do not need them to save separately for each model I need them to merge to one image.

So basically the correction need to be for export images as one per specific parameters.
Like if I choose to use the upscale and the face correction so I want the end results to be one image and not 3

**Comment by hlky** [comment]
This was already fixed [f19029a](https://github.com/hlky/stable-diffusion-webui/commit/f19029aa6b82ad9d44c4069167803a3d1575217a)

Also see https://github.com/hlky/stable-diffusion-webui/wiki/Upscalers

Just do your post-processing as post-processing, this is why these features are going to be removed from on generation, it's causing far too many issues for something that isn't really needed because you don't actually need to run gfpgan and esrgan on every single image you generate, and you dont know if you need to run it until after the image is generated

> NEED A FIX

Please avoid this kind of language, it is disrespectful

**Comment by ZeroCool940711** [comment]
@hlky I don't understand why you say upscaling and face fixing is not needed during generation and has to be done during post-processing, I personally do like those things done during generation as I do not want to do any post-processing and I just want to go to the output folder or go through the images on the mage and find the ones I like as they are and use them as they are, if I don't like how some images are I can just run another generation and get 100+ more images but if I have to process every image manually to fix the face and then upscale them so I can see how they look after that then I will most likely not do any of that and never use those features as it will be a waste of time, and btw, I've been able to create about 300 wallpapers with this tool as it is just because it has the upscaling done automatically after the generation to get high resolution images easily and I can just focus on generating a big batch of images and then pick the one I like and that's it, I'm pretty sure other people like to do the same thing, it would be better to leave things the way they are even if they are sometimes broken instead of just removing the upscaling and face fixing from generation to post-processing as that will most likely kill those features for most users that do want to use them but can't bother to waste time doing things manually.

**Comment by search620** [comment]
> 

Well sorry for my language I do not attempt to be disrespectful to anyone I just pointed out the fix that I think should have been because it makes it confusing to understand what is what. 

I will suggest maybe adding an option for the user for exporting. 
Meaning the user will have the option to export as separate files\generation or to choose to export as one merge file (png). 
That would be very useful. 

And as you can see there are users who want the option to use face correction or upscale (as I am too) so I do not think you should remove them. maybe they do not need another tab for themself because it creates confusion for some users. 
(That's not the main problem for now)

Certainly, they should be present within the option of advanced. 

I hope I am clear and if not then I would be happy to clarify so please feel free to note me.

Thanks a lot!!!! :)
