### ISSUE TITLE
2GB VRAM spike after generating images?

### ISSUE THREAD

**Issue by TheEnhas** [hlky/stable-diffusion-webui#225]
Hello, I'm been trying out this fork/UI with the --optimized-turbo parameter and it's been working fine, but after generating I tend to get this every single time:

CUDA out of memory. Tried to allocate 2.00 GiB (GPU 0; 8.00 GiB total capacity; 5.29 GiB already allocated; 282.00 MiB free; 5.37 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

This was with a single batch of 8 512x512 images. It's not the generation itself that leads to OOM, but whatever this is, which also prevents the images from being saved. In contrast I can generate 20 512x512 images with basujindal's optimized fork and I don't get the VRAM spike at the end, so something's definitely off here.

Edit: Also tried it with the regular --optimized parameter, made no difference.

**Comment by TheEnhas** [comment]
As a test to be sure I removed the environment / deleted the entire SD install and installed from scratch (just the main repo). Still the same problem.

Also after some testing it looks like optimized and optimized-turbo are using basically the same amount of VRAM as well when the former should be about 1GB less.

**Comment by EArmour** [comment]
I also noticed this happening, it does place an artificial limit on the image size my GPU should be capable of, since I have to account for the extra overhead of this momentary spike in VRAM usage at the very end. Interestingly, I tried with/without GFPGAN toggled, and it seems like this actually only happens with it OFF, which seems counter-intuitive. But I guess that might help narrow down a cause if it's something that only happens in the GFPGAN = false code branch, evidently.

Without GFPGAN:
![image](https://user-images.githubusercontent.com/1524567/187099262-a1ad7479-5d69-400f-b373-f260492d9bc0.png)

With GFPGAN:
![image](https://user-images.githubusercontent.com/1524567/187099192-f284dd66-cc73-45d7-b9ed-477b25f8d328.png)

**Comment by hlky** [comment]
Thanks for the research, this will help

**Comment by oobabooga** [comment]
Something similar happens to me: if I use txt2img with batch_count = 1 I can generate one image at a time just fine, but for batch_count of 2 or more I OOM after the first image is generated.

The line that generates the OOM is specifically 946 inside txt2img():

`        samples_ddim, _ = sampler.sample(S=ddim_steps, conditioning=conditioning, batch_size=int(x.shape[0]), shape=x[0].shape, verbose=False, unconditional_guidance_scale=cfg_scale, unconditional_conditioning=unconditional_conditioning, eta=ddim_eta, x_T=x)
`

I have tried adding torch_gc() before this line, and also in several places inside process_images(), and that didn't fix the issue. 

I hope that may help.

**Comment by oobabooga** [comment]
Pull request #267 solves this issue for me

**Comment by hlky** [comment]
@TheEnhas @EArmour reopen if #267  doesn't fix for you

**Comment by TheEnhas** [comment]
Still getting the same issue, it's always right as the images are done but before they save to the outputs folder / the preview is shown in the UI. Could the image grid preview be the problem?
