### ISSUE TITLE
Task exception was never retrieved

### ISSUE THREAD

**Issue by mikeingz** [hlky/stable-diffusion-webui#230]
Everything was working fine. I could generate some images, and I have even installed ESRGAN and GFPGAN. Both were working fine as well.

Until it didn't. No particular reason. I just did the usual : I entered my prompt, clicked on the generate button, and waited...
After a couple of minutes, still no images. I click again...still nothing. I check the command prompt and I can see that the generation didn't start. Weird but it's not a big deal, so I press CTRL C to exit, and I restart the program.
Still no error, until I click on generate, and I got these messages : 

![image](https://user-images.githubusercontent.com/2438157/187098020-2ddb974e-562e-47d2-8e99-a11aff19a27e.png)

I have deleted everything ( conda env remove -n ldo , uninstalled miniconda, deleted the full stable-diffusion-main folder) and re-installed the full package.
No error, I can still run the webui. But as soon as I try to generate, it doesn't work anymore. Always the same message.

Any idea where it can come from ?

**Comment by hlky** [comment]
I haven't seen anything like that before. Can you try updating again? I don't think anything in particular has been changed that could be related to this, but could help. Take note: #229 refactored the UI so you need to pull from [main repo](https://github.com/hlky/stable-diffusion) to get the new required files

**Comment by hlky** [comment]
I see it says Queue, are you actually using the Queue feature? It could possibly be just a gradio/queue thing because you clicked generate again while it was still generating, but I'm not sure

Can you tell me whether you are running with any command line arguments i.e. --optimized 

What are your specs? cpu, gpu, ram? 

You're not trying to access it remotely or anything? I can see you don't have share=True (which is known to cause issues due to us using Gradio Blocks based interface) but a similar bug can maybe occur with other remote access workarounds. Only wondering because I can see `Request` and `response.json` etc 

It's especially odd considering you say it was working then it wasn't. Did you update at the point it stopped working? If so that could help track down if there's been a change that broke things for you

**Comment by mikeingz** [comment]
Alright so the problem came from my proxy...I had to use a proxy to download all the stuff, but then it didn't work if it was activated. Now if I run webui.cmd before activating my proxy, then it works fine again.

It was not a bug but a proxy issue from my side. Sorry for that

**Comment by hlky** [comment]
It's ok, thanks for getting back to me, I'll close this, might add some info to the wiki about remote access workarounds
