### ISSUE TITLE
[BUG] The web interface keeps loading with more than 5 images and does not display images.

### ISSUE THREAD

**Issue by Shark1337** [hlky/stable-diffusion-webui#309]
The web interface keeps loading with more than 5 images and does not display images. although the process has finished, it does not finish showing the images, this only happens when there are more than 5 images, something strange.

![image](https://user-images.githubusercontent.com/6165744/187416563-550cf89c-dce0-4fa0-9c2e-90b945370739.png)

![image](https://user-images.githubusercontent.com/6165744/187416662-3eabfdd4-56fa-4b17-8f79-7c3d295bfe9c.png)

I am using the google cobal paid version, since I have a good memory, GPU RAM and HDD, in case it helps to solve the problem.

**Comment by hlky** [comment]
This is just due to how colab and gradio work, it's nothing something that can be fixed without a change from either colab or gradio.

Can you confirm whether you are using `batch size` or `batch count` to get 5 images? I think they need switching around in the user interface it's a little confusing because the option you want is `batch count`, `batch size` increases the memory usage because it makes more than one image at a time.

Also there's just been a change to how masking works pushed, I'm not sure if the colab updates automatically, @altryne maintains that, but it might help produce the results you're after.

**Comment by Shark1337** [comment]
First of all thank you for your great work, I am a fan of this application and its development, I know the hard work you are doing, thank you again for it.

I am using the option:

Batch count (how many batches of images to generate). 

in principle in colab always when you start the UI it looks for the latest version of it, I will check if this is the case. Thank you very much again

since colab is not a good place to host it, do you recommend any ?

**Comment by hlky** [comment]
I've switched the order for now, afaik some people use batch size 5-7 with 512x512 resolution on 24gb vram so best not to remove it
