### ISSUE TITLE
[BUG] optimized version endlessly hangs with batchsize > 1

### ISSUE THREAD

**Issue by willlllllio** [hlky/stable-diffusion-webui#337]
**Describe the bug**
When using --optimized and batchsize larger than 1 the webgui server currently gets stuck forever.

**To Reproduce**
start with --optimized
set batchsize to 3
do txt2image with any prompt
will hang forever

**Expected behavior**
it works

bug is here:
https://github.com/hlky/stable-diffusion-webui/blob/94f064fa81ffc6504543e8f2781b4d7dd00462c7/webui.py#L905

This whole `if opt.optimized: ` block should be one indention to the left, at the same level as the `modelFS.to("cpu")` above.
Currently it hangs endlessly at the time.sleep() part when the loop runs the 2nd timesince it's already on the CPU and the GPU mem doesnt go down anymore.
https://github.com/hlky/stable-diffusion-webui/blob/94f064fa81ffc6504543e8f2781b4d7dd00462c7/webui.py#L909

**Comment by hlky** [comment]
If you're using optimized you have low vram, so why are you using batch **size**? you want batch **count** surely. 

I'll wait for other optimized users to comment but I don't think this is actually an issue, just a side effect of optimized, it's probably not stuck forever, just taking a very long time because it's trying to generate 3 images at the same time with optimized mode.

**Comment by Minecorn** [comment]
I can confirm that issue. It's not caused from low VRam. I'm using Colab with latest WebUI and I have same issue. I can see from console that SD generating images but they are not appearing at WebUI.

**Comment by hlky** [comment]
@Minecorn your issue is unrelated, colab wouldn't use --optimized, first of all, there's a colab for this repo that's always working and up to date made by @altryne who works on this project as well, find it [here](https://colab.research.google.com/github/altryne/sd-webui-colab/blob/main/Stable_Diffusion_WebUi_Altryne.ipynb). I don't think that issue is happening with that colab, if it does, it's a Gradio issue which altryne can ask the people over at Gradio about as they've been in touch with us about how they can help.

**Comment by Minecorn** [comment]
@willlllllio try `no_progressbar_hiding = False`

**Comment by willlllllio** [comment]
> If you're using optimized you have low vram, so why are you using batch size? you want batch count surely.

Because on a 6GB card I can easily do pretty big batch size with optimized, so why not.

> I'll wait for other optimized users to comment but I don't think this is actually an issue, just a side effect of optimized, it's probably not stuck forever, just taking a very long time because it's trying to generate 3 images at the same time with optimized mode.

It's not generating them, it's stuck in the `time.sleep(1)` forever like I said, easy to test by just putting a print("sleeping") there, or by just trying yourself with --optimized. Also it goes to 100% without issue and is only stuck afterwords.

What happens in the loop `for i, x_sample in enumerate(x_samples_ddim):`:
1) first iteration the loop runs and does modelFS.to("cpu") it loads the model to the CPU and the mem goes down
2) second time it's already there so the memory reported by torch.cuda.memory_allocated() does not go down and it endless loops

```                 
mem = torch.cuda.memory_allocated()/1e6
modelFS.to("cpu")
while(torch.cuda.memory_allocated()/1e6 >= mem): # <---- if the model was already on the CPU the mem here will never change and go down so it will endless loop
          time.sleep(1) 
```

Once I put that one indent to the left it works perfectly now and I can do batchsize 4 without problem.

**Comment by hlky** [comment]
You might be able to do batch size 4 like that with 6gb, people with 4gb can't use it with that change, you really shouldn't be using batch size 4 on optimized anyway, batch count 4 produces 4 images but with different seeds which is probably what you want, and it will be faster than batch size 4.
