### ISSUE TITLE
[BUG] Hard drive storage space leak at the end of a large generation

### ISSUE THREAD

**Issue by mosquitobird11** [hlky/stable-diffusion-webui#347]
**Describe the bug**
Massive storage space leak at the end of a large generation set. At the end of a large generation set, the UI freezes and reserves an infinite amount of system storage (have confirmed up to 400GB). Once python is killed all of the space is unreserved and the available space on the drive goes back to normal.

**To Reproduce**
1. Generate 200+ images  at once
2. I had save grid turned off but I am not sure if this is required to repro

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Chrome 104.0.5112.102

**Comment by hlky** [comment]
Interesting, the limit for batch count was turned up on request a couple of days ago and I haven't had any reports of issues from the people who wanted batch count increased.

The UI might be freezing because it's loading 200+ images into the Gradio Gallery output, how long did you wait for it to unfreeze? I don't know why it reserves an `infinite amount of space` could you clarify what you mean? you say confirmed **up to** 400GB so the reserved space increases until you stop the script or is that just how much free space you have at the time?

What are the other settings for the batch you're trying to generate? Do the images actually save? 

What are the specs of your computer, cpu, ram?

I'll look into this but this information will help.

**Comment by hlky** [comment]
Thanks, just the generation settings then, whether you're using esrgan/gfpgan, etc

**Comment by altryne** [comment]
@hlky so some folks asked for 200? 
I personally find 200 too much, most folks don't have that kind of GPU power, and it makes it really hard to switch from 4 to 5 cause the travel distance is really small 
I think that lowering the defaults but providing a way to override it (like with the dynamic params branch I'm working on) could be a reasonable approach here

**Comment by hlky** [comment]
This is batch count which is no extra GPU power just takes n * seconds to generate 1 image, should probably rename those. There needs to be a different solution though, a text box if people want to generate a lot of images of the same prompt. Options for variation of cfg scale and steps in combination with batch count would be a nice feature too.

**Comment by mosquitobird11** [comment]
@hlky I'm gonna close this, I looked into it more and I am 99% sure this was caused by some custom local changes I had, sorry about that! Thanks a ton for this repo, it's a godsend.
