### ISSUE TITLE
Simple img2text gives division by 0 error

### ISSUE THREAD

**Issue by paciox** [hlky/stable-diffusion-webui#480]
### What happened?

Note: was using the previous version of a couple days ago and it was fine
![image](https://user-images.githubusercontent.com/6546735/188029846-2ed8fbfb-7603-4f5e-80ea-450768dc9bc1.png)

### Version

0.0.1 (Default)

### What browsers are you seeing the problem on?

Chrome

### Where are you running the webui?

Windows

### Relevant log output

```shell
Traceback (most recent call last):
  File "C:\Users\Shadow\.conda\envs\ldm\lib\site-packages\gradio\routes.py", line 247, in run_predict
    output = await app.blocks.process_api(
  File "C:\Users\Shadow\.conda\envs\ldm\lib\site-packages\gradio\blocks.py", line 641, in process_api
    predictions, duration = await self.call_function(fn_index, processed_input)
  File "C:\Users\Shadow\.conda\envs\ldm\lib\site-packages\gradio\blocks.py", line 556, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\Shadow\.conda\envs\ldm\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\Shadow\.conda\envs\ldm\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\Users\Shadow\.conda\envs\ldm\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "scripts/webui.py", line 1053, in txt2img
    output_images, seed, info, stats = process_images(
  File "scripts/webui.py", line 969, in process_images
    grid = image_grid(output_images, batch_size)
  File "scripts/webui.py", line 456, in image_grid
    cols = math.ceil(len(imgs) / rows)
ZeroDivisionError: division by zero
[MemMon] Recording max memory usage...
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jim-22** [comment]
I was about to make an issue about this same thing.

The problem seems to be these few lines:
https://github.com/hlky/stable-diffusion-webui/blob/320ea01d113096e5d99715b3adbe6b82eb9c0059/webui.py#L899
https://github.com/hlky/stable-diffusion-webui/blob/320ea01d113096e5d99715b3adbe6b82eb9c0059/webui.py#L915
https://github.com/hlky/stable-diffusion-webui/blob/320ea01d113096e5d99715b3adbe6b82eb9c0059/webui.py#L933

At some point these lines were commented out. As a result, the images never get added to the `output_images` list. 

The direct cause of the divide by zero is here:
https://github.com/hlky/stable-diffusion-webui/blob/320ea01d113096e5d99715b3adbe6b82eb9c0059/webui.py#L453-L454
`imgs` is the empty list, so `rows` becomes 0.

**Comment by Glycian** [comment]
I only get this issue if I don't save individual images so maybe it doesn't know how to get how many images there are anymore unless you save them?

**Comment by EyeDeck** [comment]
It's because of this: https://github.com/hlky/stable-diffusion-webui/blob/320ea01d113096e5d99715b3adbe6b82eb9c0059/webui.py#L944
For some reason, the part that appends to output_images is conditionalized to _only_ run when `Save individual images` is ticked. This breaks a lot of things, including outputting those images to the web UI, and processing into a grid.

Easy enough to unindent, I'll just PR it.
