### ISSUE TITLE
img2img crop error

### ISSUE THREAD

**Issue by Mary-Usagi** [hlky/stable-diffusion-webui#49]
I can't completely reproduce it, but when using img2img right now I sometimes/often get this error:

```Traceback (most recent call last):
  File "C:\tools\Miniconda\envs\ldo\lib\site-packages\gradio\routes.py", line 247, in run_predict
    output = await app.blocks.process_api(
  File "C:\tools\Miniconda\envs\ldo\lib\site-packages\gradio\blocks.py", line 639, in process_api
    processed_input = self.preprocess_data(fn_index, raw_input, state)
  File "C:\tools\Miniconda\envs\ldo\lib\site-packages\gradio\blocks.py", line 543, in preprocess_data
    processed_input.append(block.preprocess(raw_input[i]))
  File "C:\tools\Miniconda\envs\ldo\lib\site-packages\gradio\components.py", line 1546, in preprocess
    x, mask = x["image"], x["mask"]
TypeError: string indices must be integers```

**Comment by hlky** [comment]
@oldfndm implemented this, maybe he knows what the issue is

on first glance it looks like an issue with either the image or the mask, my guess would be the mask

issue title says crop, so it happening when you crop? or when you mask? or are you using the option to move an image from the gallery back to input?

also there were a couple of fixes for this feature, so make sure you're actually on the latest version
grab it from the [main repo](https://github.com/hlky/stable-diffusion)
changes from [this repo](https://github.com/hlky/stable-diffusion-webui) are synced to the main repo after a small delay in case a bug is found after a push
although of course there can still be a bug found after the change has been synced to the main repo like now (assuming youre not just on an older version)

btw i moved the issue to hlky/stable-diffusion-webui because this repo is used for development

**Comment by matttoro** [comment]
No, I too am also having this issue.

**Comment by Muskelmagier** [comment]
Same with me img2img give always the error 

Traceback (most recent call last):
  File "C:\Users\Heimann David\miniconda3\envs\ldo\lib\site-packages\gradio\routes.py", line 247, in run_predict
    output = await app.blocks.process_api(
  File "C:\Users\Heimann David\miniconda3\envs\ldo\lib\site-packages\gradio\blocks.py", line 639, in process_api
    processed_input = self.preprocess_data(fn_index, raw_input, state)
  File "C:\Users\Heimann David\miniconda3\envs\ldo\lib\site-packages\gradio\blocks.py", line 543, in preprocess_data
    processed_input.append(block.preprocess(raw_input[i]))
  File "C:\Users\Heimann David\miniconda3\envs\ldo\lib\site-packages\gradio\components.py", line 1546, in preprocess
    x, mask = x["image"], x["mask"]
TypeError: string indices must be integers

**Comment by deggua** [comment]
Switching to Mask mode and re-uploading the file seems to fix this. Appears to be because only the image is passed in Crop mode when a dict is expected.

**Comment by jansteffen** [comment]
That workaround seems to work, I switched from crop mode to mask mode, clicked the x to remove whatever it autofilled, re-added the image back in, switched back to crop mode and now it works. Maybe there's some variables being passed that are uninitialized if you don't switch to mask mode at any point?

**Comment by LiJT** [comment]
> Switching to Mask mode and re-uploading the file seems to fix this. Appears to be because only the image is passed in Crop mode when a dict is expected.

yes that the only way to fix it

**Comment by Maxxxel** [comment]
Workaround doesn't work for me. It looks like the error occurs when you zoom in/out of the image in crop mode.

**Comment by hlky** [comment]
[49-img2img-crop-error](https://github.com/hlky/stable-diffusion-webui/tree/49-img2img-crop-error) this issue is being worked on here

first thing i noticed is 
`mask_mode == 0`

this is something the person who implemented ui defaults missed

changed to `mask_mode == "Keep masked area"`

`mask_mode: str`
mask mode is a str

```
img2img_mask = gr.Radio(choices=["Keep masked area", "Regenerate only masked area"], label="Mask Mode", type="index", value=img2img_mask_modes[img2img_defaults['mask_mode']])
```

```
img2img_mask_modes = [
    "Keep masked area",
    "Regenerate only masked area",
]
```

```
img2img_defaults = {
...
    'mask_mode': 0,
...
}
```

please test, not sure what this will fix, but it's a start on the issue at least

**Comment by lmeerwood** [comment]
Been looking into this a little bit. Please excuse any incorrect terms or lack of knowledge, this is my first time using a python library like this. 

I think it's because the sketch widget that allows you to draw in the sections to remove/keep needs to have a value like so: `{'image': image, 'mask'; mask}`. By default the value of the sketch widget is a single image. So if you don't draw any masking areas on the widget then I think it will always fail.

It doesn't matter if you aren't using the masking feature, the preprocess function for the masking feature is run anyway. That's where the error is being thrown in the original post.

If you don't care about the masking feature then my hacky fix is edit `webui.py` and change line `1021` from
```
img2img_image_mask = gr.Image(value=sample_img2img, source="upload", interactive=True, type="pil", tool="sketch", visible=False)
```

to

```
img2img_image_mask = gr.Image(value=sample_img2img, source="upload", interactive=True, type="pil", tool="select", visible=False)
```
(The only change is `tool` changes from `sketch` to `select`
This will completely break the ability to mask out images, but it will stop the error for the crop functionality.

**Comment by hlky** [comment]
Steps to reproduce the error:

* img2img tab, crop mode is activated by default, click generate -> error
* img2img tab, crop mode is activated by default, click mask mode then quickly click generate -> error

What works:
* img2img tab, crop mode is activated by default, switch to mask mode, WAIT for the image to appear in mask mode, click generate -> works

https://user-images.githubusercontent.com/106811348/186908172-f85a1cc1-6a0c-42b8-adce-96a112eddc96.mp4

**Comment by oldfndm** [comment]
I fixed it but img2img in master is broken right now (it doesn't [even receive the image param](https://github.com/hlky/stable-diffusion-webui/blob/master/webui.py#L803)) so I can't make a PR.

**Comment by androm3da** [comment]
I'm on 2b1ac8daf7ea82c6c56eabab7e80ec1c33106a98 but I still seem to consistently get this error when attempting img2img.

I resized my input image (using a scale) outside of the webui and my resulting input image is smaller than 512x512.  I don't want to even crop - I'd prefer to pass the image without modifications.  But I can't tell how to unselect all the "Editor Options" to bypass the crop.
