### ISSUE TITLE
[Bug]: import _tkinter # If this fails your Python may not be configured for Tk

### ISSUE THREAD

**Issue by oc013** [hlky/stable-diffusion-webui#562]
### What happened?

Seems this was introduced via #436 @JohannesGaessler 

What is the purpose of using tkinter here? 

### Version

0.0.1 (Default)

### Relevant log output

```shell
Attaching to sd-hlky
sd-hlky  |      active environment : ldm
sd-hlky  |     active env location : /opt/conda/envs/ldm
sd-hlky  | entrypoint.sh: Launching...
sd-hlky  | Traceback (most recent call last):
sd-hlky  |   File "scripts/webui.py", line 3, in <module>
sd-hlky  |     from frontend.frontend import draw_gradio_ui
sd-hlky  |   File "/sd/frontend/frontend.py", line 3, in <module>
sd-hlky  |     from tkinter.filedialog import askopenfilename
sd-hlky  |   File "/opt/conda/envs/ldm/lib/python3.8/tkinter/__init__.py", line 36, in <module>
sd-hlky  |     import _tkinter # If this fails your Python may not be configured for Tk
sd-hlky  | ImportError: libX11.so.6: cannot open shared object file: No such file or directory
sd-hlky exited with code 1
```
```


### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by shayne** [comment]
https://github.com/hlky/stable-diffusion/discussions/93#discussioncomment-3542333

Adding this and running `$ docker compose up --build` fixed the issue for me.

**Comment by oc013** [comment]
> What is the purpose of using tkinter here?

**Comment by shayne** [comment]
> > What is the purpose of using tkinter here?

https://github.com/hlky/stable-diffusion-webui/search?q=tkinter

Looks like a file dialog

**Comment by oc013** [comment]
> > > What is the purpose of using tkinter here?
> 
> https://github.com/hlky/stable-diffusion-webui/search?q=tkinter
> 
> Looks like a file dialog

tkinter is a library for building desktop applications, surely this was the wrong library to use for a web application and should not have been merged https://gradio.app/docs/#file

**Comment by oc013** [comment]
```
sd-hlky  | Traceback (most recent call last):
sd-hlky  |   File "/opt/conda/envs/ldm/lib/python3.8/site-packages/gradio/routes.py", line 247, in run_predict
sd-hlky  |     output = await app.blocks.process_api(
sd-hlky  |   File "/opt/conda/envs/ldm/lib/python3.8/site-packages/gradio/blocks.py", line 641, in process_api
sd-hlky  |     predictions, duration = await self.call_function(fn_index, processed_input)
sd-hlky  |   File "/opt/conda/envs/ldm/lib/python3.8/site-packages/gradio/blocks.py", line 556, in call_function
sd-hlky  |     prediction = await anyio.to_thread.run_sync(
sd-hlky  |   File "/opt/conda/envs/ldm/lib/python3.8/site-packages/anyio/to_thread.py", line 31, in run_sync
sd-hlky  |     return await get_asynclib().run_sync_in_worker_thread(
sd-hlky  |   File "/opt/conda/envs/ldm/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
sd-hlky  |     return await future
sd-hlky  |   File "/opt/conda/envs/ldm/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 867, in run
sd-hlky  |     result = context.run(func, *args)
sd-hlky  |   File "/sd/frontend/frontend.py", line 168, in from_file_func
sd-hlky  |     file_path = askopenfilename()
sd-hlky  |   File "/opt/conda/envs/ldm/lib/python3.8/tkinter/filedialog.py", line 376, in askopenfilename
sd-hlky  |     return Open(**options).show()
sd-hlky  |   File "/opt/conda/envs/ldm/lib/python3.8/tkinter/commondialog.py", line 40, in show
sd-hlky  |     w = Frame(self.master)
sd-hlky  |   File "/opt/conda/envs/ldm/lib/python3.8/tkinter/__init__.py", line 3119, in __init__
sd-hlky  |     Widget.__init__(self, master, 'frame', cnf, {}, extra)
sd-hlky  |   File "/opt/conda/envs/ldm/lib/python3.8/tkinter/__init__.py", line 2561, in __init__
sd-hlky  |     BaseWidget._setup(self, master, cnf)
sd-hlky  |   File "/opt/conda/envs/ldm/lib/python3.8/tkinter/__init__.py", line 2527, in _setup
sd-hlky  |     _default_root = Tk()
sd-hlky  |   File "/opt/conda/envs/ldm/lib/python3.8/tkinter/__init__.py", line 2261, in __init__
sd-hlky  |     self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
sd-hlky  | _tkinter.TclError: no display name and no $DISPLAY environment variable
```

**Comment by JohannesGaessler** [comment]
Responsible dev here.
I implemented the loading of settings via GUI.
Because I don't know how to do this via gradio + JavaScript I just did it in a way that works for my use cases (as declared in the PR).
I was (wrongly) assuming though that all Python installations ship with Tk so I imported it statically; otherwise I would have taken the same route as with pyperclip and simply made the button unavailable if Tk is not installed.

**Comment by oc013** [comment]
Are you just trying to open a file dialog? I linked documentation on how to do so in gradio.  It doesn't make sense to use tkinter here at all because it is a web application, not a desktop application.

**Comment by JohannesGaessler** [comment]
>I linked documentation on how to do so in gradio.

Linked where?

**Comment by JohannesGaessler** [comment]
Okay, I see the thing that you linked in an earlier comment.
I was well-aware of the File element in gradio.
I did not use it because it resulted in a lot of wasted space and did not fit with the rest of the interface.
What would be needed specifically is a gradio Button that opens a file dialog (which I don't see an easy solution for in the gradio documentation).

And just to make this absolutely clear: I was well-aware that my implementation would not work for people who use different machines for client and server.
This was clearly declared in the PR and I left the decision regarding how to proceed to @hlky .
My stance is that I did an implementation that works 80% (ignoring the Tk issue) and someone else can do the remaining 20%.
If hlky had decided not to merge I simply would have kept the changes in my own private repository.

**Comment by brycedrennan** [comment]
@JohannesGaessler 
You vouched for it when you said:

> I now consider this ready to merge. 

https://github.com/hlky/stable-diffusion-webui/pull/436#issuecomment-1234786610

The changes in #436 break the docker image and the web application for ~100% of users.  This project is a web application! Using a GUI on the host is inappropriate. It's better to have a web interface that wastes space than to have a broken application. Its better to have a working application than a broken one.

Your pull request should have said something like "This isn't ready to merge since I don't know how to do the file element"

**Comment by JohannesGaessler** [comment]
@brycedrennan I did say that I consider the PR ready to merge. I also added a long list of caveats and left the decision of how to proceed up to the repository maintainer. I have no problem admitting that my assumptions regarding Tk were incorrect.

>The changes in https://github.com/hlky/stable-diffusion-webui/pull/436 break the docker image and the web application for ~100% of users. 

Adding buttons that don't work for some users does not break existing functionality.
I don't have statistics on this but I think most users use the same machine as a host and a server and for them the buttons will work.

>Your pull request should have said something like "This isn't ready to merge since I don't know how to do the file element"

I think merging a partial implementation is fine.
