### ISSUE TITLE
Need step by step tutorial on how to make Real Esrgan working

### ISSUE THREAD

**Issue by LiJT** [hlky/stable-diffusion-webui#74]
![1](https://user-images.githubusercontent.com/11270197/186957083-afdd5bb1-4b5e-4498-befb-3ec3dda4dc53.png)

I pull the realesrgan git and save it to src/realesrgan, but currently this error msg pops out. Do i have to install Real Esrgan elsewhere, then copy the folder back inside the SD folder? a bit confused.

A fool-proof tutorial on how to do that would be awesome for us none coder lol! Thank you dev

**Comment by beta-tank** [comment]
1. Put content of Real Esrgan repository to `/src/RealESRGAN`
2. Install all dependencies from this instruction https://github.com/xinntao/Real-ESRGAN#installation
3. Download .pht files https://github.com/hlky/stable-diffusion-webui#realesrgan and put to `/src/RealESRGAN/experiments/pretrained_models`

**Comment by hlky** [comment]
@LiJT 
>A fool-proof tutorial on how to do that would be awesome for us none coder 

as stated this feature is intended for advanced users for now, please refrain from requesting support in setting up something that is designated for advanced users only 

@beta-tank 
>Install all dependencies from this instruction

I am going to remove this because the exact environment.yaml requirements to integrate realesrgan automatically are undecided, notably the repo name includes a dash, if someone follows your instructions now when the feature is intended only for people who know what they are doing, then the environment.yaml setup changes, the code changes, and their setup is now broken.
Another issue is that the various guides that link to this repository are relying on a certain environment.yaml, changes cannot be made lightly as it is the main thing that causes issues with users installing this
I appreciate the effort but what I would really appreciate is people respecting the 'advanced users only' thing, and if possible, stick to using the stable release in the main repository and do not use this repository directly unless you like the bleeding edge and are an advanced user

Thank you

**Comment by Craftyawesome** [comment]
Maybe we should change install method to the upstream version? They just use pip https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/155dd2fc0c5dfde0fe9736d3170c023496fb4c39

**Comment by hlky** [comment]
@Craftyawesome as I have just stated the changes to the environment.yaml are undecided, any changes cannot be made lightly for the reasons stated, this feature is intended for advanced users only until stated otherwise.

This issued is closed.
