### ISSUE TITLE
Add api_name to gradio blocks components (API missing or hidden?)

### ISSUE THREAD

**Issue by zslittlehelper** [hlky/stable-diffusion-webui#90]
The original AUTOMATIC1111/stable-diffusion-webui has a Gradio button at the bottom to see the API.

I was planning to use it for running batches but I'm not that familiar with Gradio (or Python in general) to know whether the API is missing from this fork, or if it's simply hidden in some way?

**Comment by AK391** [comment]
since this is using gradio blocks

For a Blocks demo, the API page is not shown by default unless there is at least one event listener with an explicit api_name parameter cc: @hlky

**Comment by hlky** [comment]
Every component needs `api_name` defining to be able to be used in the API because we used gradio blocks like @AK391 said

We have a --cli version, it loads arguments from .yaml file, you might find [Scripts for batch prompt processing #59](https://github.com/hlky/stable-diffusion-webui/issues/59) useful, author of the issue will hopefully have a solution soon

**Comment by hlky** [comment]
Batch scripts implemented so functionality @zslittlehelper wanted is in effect implemented as well, closing because UI is subject to change anyway atm
