### ISSUE TITLE
share=True works but websocket fails?

### ISSUE THREAD

**Issue by altryne** [hlky/stable-diffusion-webui#96]
Previous versions exposed the webui in gradio.app domain, it was reallly great to run from mobile/mac while the GPU machine is sweating.

I've added share=True and gradio indeed loaded the tunnel, but the socket fails? for some reason

![image](https://user-images.githubusercontent.com/463317/187003459-6af82790-81c8-4740-aaf9-78679026e392.png)

**Comment by hlky** [comment]
> for some reason

exactly, i don't know why, it's not a feature i intend to support directly, you can workaround this by just accessing it over your local network, it's already exposed on all interfaces, for remote access you could use a reverse proxy/port forwarding, it's already been pointed out in similar issues that enabling authentication in demo.launch() breaks queuing, which you may or may not want, it's really not intended to be used remotely/as saas
it's likely a gradio issue related to the change to the switch to gradio blocks based user interface, if it is then i wouldn't be able to fix it even if i wanted to without forking the entire gradio repo
if you find out otherwise please do let me know and if it's a simple fix i am happy to implement it
closed for now

**Comment by altryne** [comment]
Thanks for the fast reply, seems to be a gradio issue (I reproduced it with another project)

https://github.com/gradio-app/gradio/issues/2096
